import '../styles/globals.css'
import 'bootstrap/dist/css/bootstrap.css'
// import { appWithTranslation } from 'next-i18next';

import Head from 'next/head'
import Script from 'next/script'
import Layout from '../components/Layout'



function MyApp({ Component, pageProps }) {
  return (
    <>

	 <Script src="js/main.js" /> 
    <Head>
        <title>Ecommerce APP</title>
  <meta name="description" content="Generated by create next app" />
      </Head>

      <Layout>
    <Component {...pageProps} />
      </Layout>
    
    </>
  )

  
}

export default MyApp;

